### ISSUE TITLE
Consumer API Feedback

### ISSUE THREAD

**Issue by swk003** [nhsconnect/FHIR-NRLS-API#30]
- [ ] “All requests SHALL contain a valid ‘Authorization’ header and SHALL contain an ‘Accept’ header with at least one of the following application/json+fhir or application/xml+fhir.” I don’t know why we need either header to request this resource. It’s not a secret, and if they don’t tell us what mime type they prefer, we can just pick one? - **SK: ‘Authorization’ header is mandatory. Added Accept Header query to https://github.com/nhsconnect/FHIR-NRLS-API/issues/42** 

- [ ] For Accept headers, do we allow and will we respect quality values (eg Accept: text/html, application/xml+fhir;q=0.2) in content negotiation? - **SK Added to new task: https://github.com/nhsconnect/FHIR-NRLS-API/issues/41**

- [ ] Do we also expect to handle formats specified via query parameters (eg ?_format=application/fhir+xml) and what do we do about getting both with different values? **SK Added to new task: https://github.com/nhsconnect/FHIR-NRLS-API/issues/42**

........................

1.3.1. patient

- [ ] Not sure what “This SHALL be supported for all consumer systems.” means here. Are we saying that spine SHALL accept and process this parameter, or that Consumer systems SHALL send it? If it’s the former, then an IG isn’t (in my opinion / experience) the best way to describe hard requirements to DDC. If it’s the latter than I don’t know why we’re dictating that they must do this? **SK - We need to be clear on conformance within the spec. Have added this query to https://github.com/nhsconnect/FHIR-NRLS-API/issues/36**

- [ ] I think we’ve agree that the system we’d use to refer to patients by NHS Number is https://demographics.spineservices.nhs.uk/STU3/Patient/6105551233 **SK - See https://github.com/nhsconnect/FHIR-NRLS-API/issues/8**

- [ ] 1.4 Search Response

The default behaviour where a search returns no matches is simply an empty Bundle rather than adding in an OperationOutcome. We should stick to expected FHIR norms where possible.

“Where an documentReference is returned, it SHALL include the versionId and fullUrl of the current version of the documentReference resource.” Should be “a” ? Also the bundle should include the entire resources rather than specific fields, from the FHIR spec: “…containing the results of the search as a collection of zero or more resources in a defined order.”  This would be required behaviour anyway for the Consumer to apply any filtering etc to the returned list.

Does “INVALID_NHS_NUMBER” cover a ‘patient not found’ too, I think it would be better to provide a more generic fault than to separately validate the NHS Number?

I think “ASID_CHECK_FAILED” should be absorbed into “ACCESS_DENIED”, there’s no reason for a client system to know about ASIDs (they’re just spine’s problem).

“The error codes (including other Spine error codes that are outside the scope of this API) are defined in the Spine Error or Warning Code ValueSet” I’d say that all of the errors shown are generic errors beyond a specific NRLS scope.
**SK - Have added this whole section to a new ticket: https://github.com/nhsconnect/FHIR-NRLS-API/issues/43**

- [ ] 1.5.1 Request Query
As above, the patient identifier should be based on demographics.spineservices.nhs.uk - **SK - Have added to issue: https://github.com/nhsconnect/FHIR-NRLS-API/issues/8**

- [ ] Is there no concept of limiting the search query based on ‘type’ or category, or items which ‘relatesTo’ a given one or Provider organisation? **SK - Added new ticket: https://github.com/nhsconnect/FHIR-NRLS-API/issues/44**

**Comment by wweatherill-answer** [comment]
This issue is being closed as the specific sub-issues that it contains are now being tracked by other, dedicate GitHub issues.
